name: Validate

on:
  pull_request:
    branches: main

jobs:
  first-job:
    name: validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Debug messages
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "PR number: ${{ github.event.number }}"
          echo "Commit SHA: ${{ github.sha }}"